INSERT INTO daily_stats (country_code, submission_count, last_updated) VALUES
('TW', 32510, CURRENT_TIMESTAMP),
('US', 26940, CURRENT_TIMESTAMP),
('CA', 8520, CURRENT_TIMESTAMP),
('BR', 5210, CURRENT_TIMESTAMP),
('FR', 12000, CURRENT_TIMESTAMP),
('GB', 12850, CURRENT_TIMESTAMP),
('IN', 14120, CURRENT_TIMESTAMP),
('AU', 1240, CURRENT_TIMESTAMP),
('ZA', 1840, CURRENT_TIMESTAMP)
ON CONFLICT (country_code) DO NOTHING;
