name: GCE Auto Deployment

on:
  push:
    branches:
      - main # Triggers when code is pushed or a PR is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to GCE
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCE_SSH_IP }}
          username: ${{ secrets.GCE_SSH_USER }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml,backend/,frontend/"
          target: "/home/${{ secrets.GCE_SSH_USER }}/truehuman"
          rm: false

      - name: Deploy to Google Compute Engine via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_SSH_IP }}
          username: ${{ secrets.GCE_SSH_USER }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.GCE_SSH_USER }}/truehuman
            docker compose down --remove-orphans
            docker compose up -d --build
